version: '3'
services:
    webserver:
        container_name: webserver
        image: nginx:alpine
        ports:
            - ${WEBSERVER_PORT:-80}:80
        volumes:
            - .:/var/www
            - .docker/webserver/nginx.conf:/etc/nginx/nginx.conf
            - .docker/webserver/sites/:/etc/nginx/conf.d
        networks:
            - api-network
        depends_on:
          - api
          - phpmyadmin
    api:
      container_name: api
      build:
        context: .
        args:
          UID: ${UID:-1000}
          GID: ${GID:-1000}
      image: desafio-inpeace-api:latest
      networks:
        - api-network
      depends_on:
        - mysql
    mysql:
        container_name: mysql
        image: mysql:8.0
        volumes:
            - "mysqlvolume:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
        networks:
          - api-network
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin:5.1
        environment:
            PMA_HOST: '${DB_HOST}'
            PMA_USER: '${DB_USERNAME}'
            PMA_PASSWORD: '${DB_PASSWORD}'
        networks:
          - api-network
        depends_on:
          - mysql
networks:
  api-network:
volumes:
  mysqlvolume:
